### ISSUE TITLE
Use of "name" attribute in definitions

### ISSUE THREAD

**Issue by chsigi** [pynag/pynag#219]
Given a valid icinga host definition

    define host {
        host_name         A
        alias             Host A
        max_check_attempts       10
        notification_interval    10
        check_period             24x7
        notification_period      24x7
    }

pynag assumes on various occasions (get_by_name(), reload_cache(), ....) that the
definition should have an attribute called "name" and fails.

Am I missing something here? I could find no reference to a "name" attribute in the icinga 1.11 documentation.

It seems as if the dynamically added name property should extract its value not from "name" but
"host_name",  "contact_name", ...

If this is indeed a bug, I would be more than happy to help!

**Comment by palli** [comment]
Hey Christoph.

Name is a valid attribute for all objects (which is why you might not have seen it in host specific docs). Its used for templates (so for example your configuration probably has a host already with no hostname and name=generic-host).

The abstract term for host_name contact_name etc is shortname.

So get_by_shortname() is probably what you were looking for.

**Comment by palli** [comment]
Marking as closed until further notice. Don't hesitate to reopen if you believe there is a bug in here.
