### ISSUE TITLE
Find which hostgroups a host belong to.

### ISSUE THREAD

**Issue by wangdepeng** [pynag/pynag#239]
There are two ways we can define which hostgroups a host belongs to.
1) Define which hostgroups when defining a host
Example:
define host{
        host_name               A
        hostgroups              Group_B, Group_C
        }
2) Define which hosts belong to hostgroup when defining hostgroup.
Example:
define hostgroup{
hostgroup_name	Group_B
members	D
   	}

pynag can parse the first one but fail to parse the second one. Is there a way to fix this?
Thanks,

**Comment by toddejohnson** [comment]
This is parsed but hidden away in the hostgroup['members'] would be nice to merge the lists.

**Comment by palli** [comment]
Yeah this is done intentionally since mangling direct and indirect memberships together can get really messy really fast.

pynag uses the term "effective" members, so in your examples above you get different results depending on if you do pynag.Model.Host.get("A").get_hostsgroups() vs. pynag.Model.Host.get("A").get_effective_hostgroups().

The first one will get the hostgroups that are defined on the current object, the second one will do a more expensive parse and look for other objects that that include the current one.

Hope this helps!
